# Generated by Django 4.2.16 on 2024-11-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_genius", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
