# Generated by Django 4.2.16 on 2024-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_genius", "0002_recipeingredient_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
