# Generated by Django 4.2.16 on 2024-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_genius", "0003_alter_recipeingredient_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="url",
            field=models.CharField(max_length=300),
        ),
    ]
