# Generated by Django 4.2.16 on 2024-12-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_genius", "0004_alter_recipe_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.CharField(default="dakva", max_length=300),
            preserve_default=False,
        ),
    ]
